### PR TITLE
[add Arabic support]

### PR DESCRIPTION
**Pull request by MuhamedFathy**

### CODE REVIEW

**Comment by curioustechizen** [comment]
Thanks for submitting this PR. I will merge it later this weekend.

**Comment by curioustechizen** [comment]
@MuhamedFathy The PR has been merged. It will be included in the next release. I would prefer to wait till there are a few more changes before making another release though.

**Comment by curioustechizen** [comment]
@MuhamedFathy Included in Release 1.3.3

**Comment by MuhamedFathy** [comment]
Awesome, Thanks a lot.

**Pull request merged**
