### PR TITLE
Additional translations

### PR DESCRIPTION
**Pull request by Dev-iL**
As per #21

### CODE REVIEW

**Comment by Dev-iL** [comment]
I meant only for the first 3 commits (those related to translations) to go into the pull request. The last one addresses issue #28.

**Comment by curioustechizen** [comment]
@Dev-iL would you mind sending the last commit as a separate PR? I would like to merge the PR for the translations separately

**Comment by Dev-iL** [comment]
@Kiran I'll hopefully get to it today. Don't forget you can always
"cherry-pick" specific commits from a larger PR.

**Comment by Dev-iL** [comment]
@curioustechizen I have rearranged my commits and now only the translations are in this PR. Would you still like me to submit the "data-binding example commit" as a PR, or will that just be a waste of everybody's time..?

**Comment by curioustechizen** [comment]
@Dev-iL Thanks a ton. I somehow forgot about cherrypicking (something that I don't have to do very often). I think a data binding sample would be very helpful to others.

**Comment by Dev-iL** [comment]
@curioustechizen Could you please merge the translations PR first? I don't see how I can create another PR w/o also including the commits that are already in this one....

**Pull request merged**
